version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test-backend
    env_file:
      - .env
    ports:
      - "8080:8080"
    command: [
      "java",
      "-Xmx2048m",
      "-jar",
      "/app.jar",
      "--server.port=8080"
    ]
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres:/data/postgres
    ports:
      - "2347:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"

volumes:
  postgres:
  pgadmin: